title:            limeng
description:      Limeng's personal blog.
url:              limmeng.github.io
signoff:          limeng
disqus_shortname: limmeng
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         主页
    url:          /
  - name:         随笔
    url:          /essay
  - name:         技术
    url:          /technology
  - name:         游戏
    url:          /game
  - name:         关于
    url:          /about
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
excerpt_separator: ""

timezone: Asia/Shanghai

# pagination
paginate: 15
paginate_path: "/page:num/"

# default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "essay"
      disqus: "y"
